### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by kjagiello** [uppsaladatavetare/datavetenskap.nu.old#1]
En action list med punkter som måste göras innan vi är klara med flytten till Pelican:

- [x] a) Flytta över alla blogginlägg (säkerställ att de ser bra ut)
- [x] b) Flytta över alla statiska sidor
- [x] c) Flytta över alla bilder/bilagor till något annat ställe. Hur stora är filerna? Är det vettigt att ha dem i repot (den enklaste lösningen)?
- [x] d) Continuous deployment (automatisk build och deploy)
- [x] e) Fixa länkarna på /foreningar/ud-2/styrelsen/
- [x] f) Implementera en check som kollar döda länkar på sajten?
- [x] g) Flytta in CSS/JS i repot
- [x] h) Skriv README och förklara för folk hur man bidrar med content 
- [x] i) Pagineringslänkarna borde mappa mot dem på nuvarande sajten
- [x] j) "Edit on GitHub"-länk
- [x] k) Highlight av aktiva länkar i menyn

Deploy checklist:

- [x] Se över README-filen en gång till.
- [x] Bjud in PR-amanuensen och informationsansvarige till @uppsaladatavetare/website-managers.
- [x] Byt domännamn till "datavetenskap.nu" i configen
- [x] Merge till master
- [x] Master borde vara en protected branch
- [x] Meddela Olle om ändringen
- [x] Peka om domännamnet (http://www.it.uu.se/internt/web/bugzilla/enter_bug.cgi?product=Datordrift)

Det vore även bra att komma överens om vilket språk vi kommer använda i det här repot. Det känns som att svenska är mest passande, då allt innehåll på hemsidan är ju på svenska.

**Comment by flaeppe** [comment]
Dags att uppdatera listan lite?

Har för mig vi diskuterade att det är bättre att vi håller språket på engelska, för eventuella internationella studenter som engagerar sig i föreningen och då också det här repot. Så det blir lättare överlag för alla att följa med, det skadar ju ingen att det är på engelska. Dock så borde content hålla sig mestadels till Svenska, möjligtvis att Engelska kan vara okej, det kan få bero på vad det är för content som kommer upp.

Visst skulle vi också kunna bocka av några tasks (i.e. `c)`) har för mig att du nämnt den är löst.

**Comment by kjagiello** [comment]
Alright. Styrelsen har godkänt idéen, så det är bara att gå live med nya sajten. Det mesta verkar vara klart. Lägger upp en slutlig TODO-lista med saker att göra innan vi kan deploya.

**Comment by kjagiello** [comment]
Nu väntar vi på ompekningen: http://www.it.uu.se/internt/web/bugzilla/show_bug.cgi?id=10201

**Comment by kjagiello** [comment]
We are live!!!
