### ISSUE TITLE
Homepage appears not to be syncing with master

### ISSUE THREAD

**Issue by MiltinMI** [uppsaladatavetare/datavetenskap.nu.old#17]
12-09_hostmotesprotokoll.rst was added to blog and filarkiv.rst was updated. These changes were successfully pushed to master, although the homepage hasn't changed or "re-rendered".

What has broken down and if I am guilty for this; what can I do to prevent this from happening in the future?

**Comment by MiltinMI** [comment]
This bug seems to date back further than I first thought as "DV-Builds" still can be found and displayed on the page.

**Comment by kjagiello** [comment]
The problem seems to be following:
```
pelican /home/travis/build/uppsaladatavetare/datavetenskap.nu/content -o /home/travis/build/uppsaladatavetare/datavetenskap.nu/output -s /home/travis/build/uppsaladatavetare/datavetenskap.nu/pelicanconf.py 

/home/travis/build/uppsaladatavetare/datavetenskap.nu/content/blog/2017/12-09_hostmotesprotokoll.rst:2: (WARNING/2) Title underline too short.


Mötesprotokoll för Höstmötet 2017

##############################

make: *** [html] Error 12
```

Source: https://travis-ci.org/uppsaladatavetare/datavetenskap.nu/builds/317644692

**Comment by kjagiello** [comment]
Weird that warnings cause the build to fail. Definitely something I should look into!

**Comment by MiltinMI** [comment]
Title underline was missing 3 hashes, preventing the homepage from building.
Thank you kjagiello for digging into this and finding the cause so quickly.
