### ISSUE TITLE
Viewing visitor statistics 

### ISSUE THREAD

**Issue by KristofferSmedlund** [uppsaladatavetare/datavetenskap.nu.old#18]
Is there any way to view the visitor statistics of datavetenskap.nu?

**Comment by MiltinMI** [comment]
https://github.com/uppsaladatavetare/datavetenskap.nu/graphs/traffic

**Comment by KristofferSmedlund** [comment]
@MiltinMI  is that the statistics for the repo visitors or the github pages page datavetenskap.nu?

**Comment by MiltinMI** [comment]
Good question, I assumed it refered to how people reached the homepage. 
But now it all seems so unclear!

**Comment by kjagiello** [comment]
No, there are is no tracking installed on the site. We could start using Google Analytics for that.

**Comment by kjagiello** [comment]
ping @Maxxen

**Comment by Maxxen** [comment]
Added to my to do list. I'll look into this further once this period is over and I can afford to really sit down with the website. I understand this could probably be valuable information for PR when it comes to measuring engagement and interest both from inside and outside the program, but I wasn't even aware that it was a possibility with the current setup.

**Comment by kjagiello** [comment]
It’s possible from the technical perspective. Just let me know if you need
any assistance.

fre 2 mars 2018 kl. 16:37 skrev Max Gabrielsson <notifications@github.com>:

**Comment by Maxxen** [comment]
Solution proposed in #21
