### ISSUE TITLE
Missing SSL

### ISSUE THREAD

**Issue by freddedotme** [uppsaladatavetare/datavetenskap.nu.old#27]
I'm currently trying to fetch from your Atom feed for a news feed I'm making for Kodstugan.
Would it be possible if someone have time over to enforce HTTPS via Github or use something like letsencrypt/Cloudflare? 😊

Repo: https://github.com/Kodstugan/kodstugan-foo
Website: https://foo.kodstugan.io

Cheers!

**Comment by Maxxen** [comment]
Trying to enforce with github, It looks like I don't have access to the repo settings tab since I just have member status. Are there any possibilities to bump me up to admin within UD or otherwise grant me persmission?  Ping @kjagiello

**Comment by kjagiello** [comment]
I've given you admin access to this repository @Maxxen According to what I see in the settings, we will need ask the administrators at UU to adjust the DNS-records.

**Comment by Maxxen** [comment]
I don't really know who to contact (can't find any "Webbmaster/admin" role in institutionens contact list but after digging through some really old emails in the dv-info gmail it looks like Olle has (or had) some sort of responsibility over the domain. I sent him an e-mail asking for further assistance/pointers.

**Comment by kjagiello** [comment]
You can do it via IT department's bugzilla. You can see my ticket from last year regarding DNS here: http://www.it.uu.se/internt/web/bugzilla/show_bug.cgi?id=10201

**Comment by Maxxen** [comment]
Thanks! I've submitted a report [here](http://www.it.uu.se/internt/web/bugzilla/show_bug.cgi?id=11484).

**Comment by Maxxen** [comment]
The site is now using HTTPS, although were currently serving mixed content. Ill work on updating the tags, should have a fix ready soon-ish.

**Comment by Maxxen** [comment]
Alright 😅, after some fiddling with pelican the site now serves all content using https!

**Comment by kjagiello** [comment]
Nice one!
